export type LocationHazardFlavor =
	| "none"
	// Moon
	| "dust_oceans"
	| "regolith_microbes"
	// Phobos
	| "hollow"
	// Mars
	| "seasonal_plant_life"
	// Venus
	| "extreme_heat_and_pressure"
	| "liquid_water_oceans"
	| "wetland_life"
	// Ceres
	| "water_ice"

	// Io
	| "volcanic_activity"
	// Europa
	| "thick_ice"
	| "thin_ice"
	| "aquatic_life_thin_ice"
	| "unknown_force"
	// Ganymede
	| "rock_and_ice_crust"
	// Enceladus
	| "geysers"
	// Titan
	| "nitrogen_methane_atmosphere"
	| "liquid_hydrocarbons"
	| "methane_based_life"
	// Saturn
	| "debris_from_rings";
